### ISSUE TITLE
Compatibility with Warhammer 4e

### ISSUE THREAD

**Issue by Sasmira** [AmazingVanish/apsj4mej#1]
Hello Hello, 

Is it possible to do your module compatible with the Warhammer 4e system? there are some readability problems ... a screenshot is more telling
<img src="https://puu.sh/IHGzM/5ef4aced7f.jpg">

thx for your help and good luck !
S.

**Comment by AmazingVanish** [comment]
Hmm. I assume you're talking about the very white areas? I'll try installing Warhammer 4e and see if there's anything I can do.

**Comment by Sasmira** [comment]
> 

Yes it is ... and just with Monk's Enhanced Journal 
<img src="https://puu.sh/IHH3f/78ab1eb7a2.jpg">

**Comment by AmazingVanish** [comment]
Fixed in v 1.2.5 rolling out now.
![WH4e-ss](https://user-images.githubusercontent.com/192720/152897961-ca0702c5-74b9-4ed3-b7aa-2b3e96978a38.png)

**Comment by Sasmira** [comment]
Nice job !
