### ISSUE TITLE
Conflicts with Custom Fonts module

### ISSUE THREAD

**Issue by Jonwh25** [AmazingVanish/apsj4mej#12]
Looks like it would be better if you just pointed people to download the fonts and use the custom fonts module in combination with yours.  Whenever I have both modules together, I get 404 timeouts and other issues that appear upon game loading in the console log.

**Comment by AmazingVanish** [comment]
My experiences with the Custom Fonts module, prior author and current, have been less than satisfactory. I also added the custom fonts in this module specifically so users would have access to them without needing another module.

I guess what I'm saying is that you will have to choose which mod provides more value to you and drop the other.
