### ISSUE TITLE
Will it be made v10 compatible?

### ISSUE THREAD

**Issue by DreamingHero1997** [AmazingVanish/apsj4mej#15]
Hey I absolutely love this mod and I was wondering if there are plans to make it v10 compatible, the new menu is especially a big upgrade over the lackluster standard menu that doesn't work outside of journals.

**Comment by AmazingVanish** [comment]
Sort of, yes. I can't say much about it yet, but a big change is coming. Until then you can play around with https://github.com/VanishsVault/apsjournal
