### ISSUE TITLE
Conflict with DFreds Effects Panel

### ISSUE THREAD

**Issue by weepingminotaur** [AmazingVanish/apsj4mej#5]
A big red speech bubble appears over all effects shown in DFreds Effects Panel. Find the Culprit reveals that it's Arius Planeswalker's Stylish Journal for Monk's Enhanced Journal causing the issue. See attached screenshot.
<img width="207" alt="Screen Shot 2022-02-08 at 8 30 21 PM" src="https://user-images.githubusercontent.com/90105219/153108913-43ead6fe-0084-4d2b-b108-9baca9709705.png">

**Comment by AmazingVanish** [comment]
D'oh! We must be using the same class name. Shame on us for not naming spacing our efforts. I'll get that fixed for tonight's release. Thanks for bringing it up!

**Comment by weepingminotaur** [comment]
Thanks for the quick response!

**Comment by AmazingVanish** [comment]
Fixed in v 1.3.0 rolling out soon.
