### ISSUE TITLE
Error in console log

### ISSUE THREAD

**Issue by ghost** [AmazingVanish/apsj4mej#7]
Howdy! Getting this error in the console log:

![image](https://user-images.githubusercontent.com/30846057/155865941-4981b3bc-3bf8-4990-aeda-5bae36b56b77.png)

Narrowed it down with "Find the Culprit" to this list:

![image](https://user-images.githubusercontent.com/30846057/155865963-6b3fc754-8c7c-4ba1-a830-24205bdfa19f.png)

The setting that's failing to find is 'apsj4mej.apsj4mejColorTheme' if that helps.

Thanks!

**Comment by AmazingVanish** [comment]
Thanks for the heads up! I removed the offending code as it shouldn't be needed anymore.
Rolling out as v2.5.2 shortly.

**Comment by ghost** [comment]
Yep, didn't look like it had any untoward effects, but figured I should bring it to your attention. Thanks!
