### ISSUE TITLE
[Feature Request]: Multiple color options for Read Aloud template

### ISSUE THREAD

**Issue by weepingminotaur** [AmazingVanish/apsj4mej#9]
I'd love to be able to represent dialog in a journal entry with two or three characters talking in different-colored read aloud templates.

**Comment by AmazingVanish** [comment]
@weepingminotaur Hmm. I should be able to provide multiple color options to choose from. Interesting.

**Comment by AmazingVanish** [comment]
Implemented as Dialogue blocks, offered in all colors with icon on left or right.
